name: sync-common-types-files
on:
  push:
    branches:
      - main
    paths: 
      - 'specification/common-types/**'
  workflow_dispatch:
jobs:
  sync-common-types-files:
    name: sync-common-types-files
    runs-on: ubuntu-latest
    steps:
        - name: Generate token
          id: generate_token
          uses: tibdex/github-app-token@v1
          # https://github.com/marketplace/actions/github-app-token
          with:
            app_id: ${{ secrets.APP_ID }}
            private_key: ${{ secrets.PRIVATE_KEY }}
        - name: Use token
          env:
            TOKEN: ${{ steps.generate_token.outputs.token }}
          run: |
            echo "The generated token is masked: ${TOKEN}"
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Repo File Sync Action
          uses: BetaHuhn/repo-file-sync-action@v1
          # https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-action-inputs
          with:
            GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
            CONFIG_PATH: .github/sync-config.yml
            ASSIGNEES: |
              JackTn
            PR_LABELS: false