 name: sync-common-types-files
 on: 
   push:
     branches:
       - main
     paths: 
       - 'specification/common-types/**'
   schedule:
       - cron: '0 17 * * *'
       - cron: '*/30 * * * *'
   workflow_dispatch:
 jobs:
   sync-common-types-files-1:
     name: sync-common-types-files-1
     runs-on: ubuntu-latest
     steps:
       - name: checkoutV2 
         uses: actions/checkout@v2
       - name: sync-common-types-files
         uses: ./
         with:
            SOURCE: test-repo-billy/azure-rest-api-specs@main
            DEST: test-repo-billy/azure-rest-api-specs-pr@RPSaaSMaster
            FILE_PATH: specification/common-types
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
   sync-common-types-files-2:
     name: sync-common-types-files
     runs-on: ubuntu-latest
     steps:
       - name: checkoutV2 
         uses: actions/checkout@v2
       - name: sync-common-types-files
         uses: ./
         with:
            SOURCE: test-repo-billy/azure-rest-api-specs@main
            DEST: test-repo-billy/azure-rest-api-specs-pr@RPSaaSDev
            FILE_PATH: specification/common-types
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
